// Parser exports
export { Parser } from "./terminal/Parser";
export type { ParserOptions } from "./terminal/ParserOptions";
export type { ParserHandlers } from "./terminal/ParserOptions";

// Terminal emulation types
export type {
  // ESC types
  EscBase,
  EscMessage,
  EscSaveCursor,
  EscRestoreCursor,
  // CSI types
  CsiBase,
  CsiMessage,
  CsiCursorUp,
  CsiCursorDown,
  CsiCursorForward,
  CsiCursorBackward,
  CsiCursorNextLine,
  CsiCursorPrevLine,
  CsiCursorHorizontalAbsolute,
  CsiCursorPosition,
  CsiEraseInDisplayMode,
  CsiEraseInDisplay,
  CsiEraseInLineMode,
  CsiEraseInLine,
  CsiScrollUp,
  CsiScrollDown,
  CsiSetScrollRegion,
  CsiSaveCursorPosition,
  CsiRestoreCursorPosition,
  CsiDecModeSet,
  CsiDecModeReset,
  CsiSetCursorStyle,
  CsiUnknown,
  // SGR types
  SgrBase,
  SgrMessage,
  SgrReset,
  SgrBold,
  SgrFaint,
  SgrItalic,
  SgrUnderline,
  SgrUnderlineStyle,
  SgrSlowBlink,
  SgrRapidBlink,
  SgrInverse,
  SgrHidden,
  SgrStrikethrough,
  SgrFont,
  SgrFraktur,
  SgrDoubleUnderline,
  SgrNormalIntensity,
  SgrNotItalic,
  SgrNotUnderlined,
  SgrNotBlinking,
  SgrProportionalSpacing,
  SgrNotInverse,
  SgrNotHidden,
  SgrNotStrikethrough,
  SgrColorType,
  SgrNamedColor,
  SgrForegroundColor,
  SgrDefaultForeground,
  SgrBackgroundColor,
  SgrDefaultBackground,
  SgrDisableProportionalSpacing,
  SgrFramed,
  SgrEncircled,
  SgrOverlined,
  SgrNotFramed,
  SgrNotOverlined,
  SgrUnderlineColor,
  SgrDefaultUnderlineColor,
  SgrIdeogram,
  SgrSuperscript,
  SgrSubscript,
  SgrNotSuperscriptSubscript,
  SgrUnknown,
} from "./terminal/TerminalEmulationTypes";
